from __future__ import annotations

from pathlib import Path
from typing import Iterable, Optional, Any
import math
import logging
from contextlib import contextmanager

from rdflib import Graph, RDF, RDFS, OWL, URIRef, Literal, Namespace
from rdflib.term import _toPythonMapping


RDF_FORMAT_BY_SUFFIX = {
    ".ttl": "turtle",
    ".rdf": "xml",
    ".xml": "xml",
    ".nt": "nt",
    ".nq": "nquads",
    ".jsonld": "json-ld",
    ".trig": "trig",
}

_EPSILON = 1e-12



@contextmanager
def suppress_rdflib_datatype_conversion_logs():
    """Silence RDFlib datatype-conversion errors during parsing.

    RDFlib logs messages such as "Failed to convert Literal lexical form to value"
    when a typed literal is syntactically valid Turtle but has an invalid lexical
    value for its XSD datatype, e.g. "1,5"^^xsd:decimal. These messages are
    not Python exceptions and otherwise bypass our extended-report mechanism.
    """
    term_logger = logging.getLogger("rdflib.term")
    old_disabled = term_logger.disabled
    old_level = term_logger.level
    term_logger.disabled = True
    try:
        yield
    finally:
        term_logger.disabled = old_disabled
        term_logger.setLevel(old_level)


def find_invalid_xsd_literals(g: Graph, limit: int = 100) -> list[dict[str, str]]:
    """Return typed literals whose lexical form cannot be converted by RDFlib.

    RDF allows typed literals to be parsed even when their lexical form is not
    valid for the declared datatype. For example, "1,5"^^xsd:decimal is valid
    Turtle syntax but not a valid xsd:decimal lexical form. This helper detects
    these cases so they can be written to extended-report.txt without polluting
    stderr/stdout.
    """
    invalid: list[dict[str, str]] = []
    with suppress_rdflib_datatype_conversion_logs():
        for s, p, o in g.triples((None, None, None)):
            if not isinstance(o, Literal) or o.datatype is None:
                continue
            if o.datatype not in _toPythonMapping:
                continue
            converted = o.toPython()
            if converted is o:
                invalid.append({
                    "subject": str(s),
                    "predicate": str(p),
                    "literal": str(o),
                    "datatype": str(o.datatype),
                })
                if len(invalid) >= limit:
                    break
    return invalid

def clean_float(value: float | None, epsilon: float = _EPSILON) -> float | None:
    """Normalise tiny floating point artefacts generated by cosine/linear algebra operations."""
    if value is None:
        return None
    if isinstance(value, float):
        if math.isnan(value):
            return value
        if abs(value) < epsilon:
            return 0.0
        if abs(value - 1.0) < epsilon:
            return 1.0
    return value



@contextmanager
def suppress_rdflib_datatype_conversion_logs():
    """Silence RDFlib datatype-conversion errors during parsing.

    RDFlib logs messages such as "Failed to convert Literal lexical form to value"
    when a typed literal is syntactically valid Turtle but has an invalid lexical
    value for its XSD datatype, e.g. "1,5"^^xsd:decimal. These messages are
    not Python exceptions and otherwise bypass our extended-report mechanism.
    """
    term_logger = logging.getLogger("rdflib.term")
    old_disabled = term_logger.disabled
    old_level = term_logger.level
    term_logger.disabled = True
    try:
        yield
    finally:
        term_logger.disabled = old_disabled
        term_logger.setLevel(old_level)


def find_invalid_xsd_literals(g: Graph, limit: int = 100) -> list[dict[str, str]]:
    """Return typed literals whose lexical form cannot be converted by RDFlib.

    RDF allows typed literals to be parsed even when their lexical form is not
    valid for the declared datatype. For example, "1,5"^^xsd:decimal is valid
    Turtle syntax but not a valid xsd:decimal lexical form. This helper detects
    these cases so they can be written to extended-report.txt without polluting
    stderr/stdout.
    """
    invalid: list[dict[str, str]] = []
    with suppress_rdflib_datatype_conversion_logs():
        for s, p, o in g.triples((None, None, None)):
            if not isinstance(o, Literal) or o.datatype is None:
                continue
            if o.datatype not in _toPythonMapping:
                continue
            converted = o.toPython()
            if converted is o:
                invalid.append({
                    "subject": str(s),
                    "predicate": str(p),
                    "literal": str(o),
                    "datatype": str(o.datatype),
                })
                if len(invalid) >= limit:
                    break
    return invalid

def clean_float_dict(values: dict) -> dict:
    return {k: clean_float(v) if isinstance(v, float) else v for k, v in values.items()}


def safe_divide(numerator: float, denominator: float, default: float | None = None) -> float | None:
    if denominator == 0:
        return default
    return numerator / denominator


def parse_graph(path: str | Path, fmt: str | None = None) -> Graph:
    p = Path(path)
    if fmt is None:
        fmt = RDF_FORMAT_BY_SUFFIX.get(p.suffix.lower(), "turtle")
    g = Graph()
    with suppress_rdflib_datatype_conversion_logs():
        g.parse(str(p), format=fmt)
    return g


def graph_to_triple_set(g: Graph) -> set[tuple[Any, Any, Any]]:
    return set(g.triples((None, None, None)))


def load_ontology_classes(ontology_graph: Graph) -> set:
    return {s for s, _, _ in ontology_graph.triples((None, RDF.type, OWL.Class))}


def load_ontology_properties(ontology_graph: Graph) -> set:
    props = set()
    for cls in (OWL.ObjectProperty, OWL.DatatypeProperty, RDF.Property):
        props |= {s for s, _, _ in ontology_graph.triples((None, RDF.type, cls))}
    return props


def typed_instance_triples(g: Graph, ontology_classes: set) -> set:
    return {(s, p, o) for s, p, o in g.triples((None, RDF.type, None)) if o in ontology_classes}


def property_assertion_triples(g: Graph, ontology_properties: set) -> set:
    return {(s, p, o) for s, p, o in g.triples((None, None, None)) if p in ontology_properties and p != RDF.type}


def datatype_literals(g: Graph) -> set:
    return {o for _, _, o in g.triples((None, None, None)) if isinstance(o, Literal) and o.datatype is not None}


def language_tagged_literals(g: Graph) -> set:
    return {o for _, _, o in g.triples((None, None, None)) if isinstance(o, Literal) and o.language is not None}


def predicate_object_pairs(g: Graph) -> set[tuple[Any, Any]]:
    return {(p, o) for _, p, o in g.triples((None, None, None))}


def literals_by_property(g: Graph) -> dict[Any, list[str]]:
    result: dict[Any, list[str]] = {}
    for _, p, o in g.triples((None, None, None)):
        if isinstance(o, Literal):
            result.setdefault(p, []).append(str(o))
    return result


def mean(values: Iterable[float]) -> float | None:
    vals = [v for v in values if v is not None and not (isinstance(v, float) and math.isnan(v))]
    if not vals:
        return None
    return clean_float(sum(vals) / len(vals))


def std(values: Iterable[float]) -> float | None:
    vals = [v for v in values if v is not None and not (isinstance(v, float) and math.isnan(v))]
    if not vals:
        return None
    m = sum(vals) / len(vals)
    return clean_float(math.sqrt(sum((x - m) ** 2 for x in vals) / len(vals)))


def as_csv_value(value):
    if value is None:
        return ""
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, (list, set, tuple)):
        return "|".join(str(v) for v in value)
    return value


def count_ttl_files(path: str | Path) -> int:
    return len(list(Path(path).rglob("*.ttl")))


def count_triples_in_directory(path: str | Path, logger=None) -> int:
    total = 0
    for ttl in Path(path).rglob("*.ttl"):
        try:
            total += len(parse_graph(ttl, "turtle"))
        except Exception as e:
            if logger:
                logger.log("count_triples_in_directory", "Could not parse generated RDF file while counting triples.",
                           pred_file=str(ttl), exception=e)
    return total


def default_allowed_predicates() -> set:
    """Predicates that are part of RDF/RDFS/OWL metadata and must not be treated as ontology hallucinations.

    The benchmark metric is meant to detect invented domain predicates. The RDF typing predicate is
    required to express class membership and should never be reported as hallucinated.
    """
    return {RDF.type, RDFS.label, RDFS.comment, RDFS.seeAlso, OWL.sameAs}
